export function getExampleFetchAllAccountFinancialsResponse() {
  return {
    data: {
      identity: {
        id: "identity-9ArKqNCmhnxU1sbZGd91BwDt8Wt",
        accounts: {
          pageInfo: {
            hasNextPage: false,
            endCursor: "MTU",
            __typename: "PageInfo",
          },
          edges: [
            {
              cursor: "MQ",
              node: {
                id: "non-registered-ki2mgqzx",
                applicationFamilyId:
                  "application_family-1xHC4nCktjP9Zfx95bcBPuUqyk",
                archivedAt: "2023-09-09T16:55:19Z",
                branch: "TR",
                category: "NON_REGISTERED",
                closedAt: "2023-09-09T16:55:19Z",
                createdAt: "2020-03-20T22:56:31Z",
                currency: "CAD",
                requiredIdentityVerification: "fintracVerification",
                unifiedAccountType: "SELF_DIRECTED_NON_REGISTERED",
                updatedAt: "2023-09-09T16:55:35Z",
                nickname: null,
                status: "closed",
                accountOwnerConfiguration: null,
                accountFeatures: [
                  {
                    name: "FULLY_PAID_LENDING",
                    enabled: true,
                    __typename: "AccountFeature",
                  },
                ],
                accountOwners: [
                  {
                    accountId: "non-registered-ki2mgqzx",
                    identityId: "identity-9ArKqNCmhnxU1sbZGd91BwDt8Wt",
                    accountNickname: null,
                    clientCanonicalId: "user-tsv6qxw1l8c",
                    accountOpeningAgreementsSigned: true,
                    name: " Li",
                    email: "ylilarry@gmail.com",
                    ownershipType: "primary",
                    activeInvitation: null,
                    __typename: "AccountOwner",
                  },
                ],
                type: "non_registered",
                __typename: "Account",
                custodianAccounts: [
                  {
                    id: "H24217004CAD",
                    branch: "TR",
                    countryCode: "CA",
                    createdAt: "2020-03-20T22:56:32Z",
                    currency: "CAD",
                    custodian: "so",
                    status: "closed",
                    updatedAt: "2023-11-11T14:41:22Z",
                    __typename: "CustodianAccount",
                    financials: {
                      current: {
                        deposits: {
                          amount: "0",
                          cents: 0,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        earnings: {
                          amount: "0",
                          cents: 0,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        netDeposits: {
                          amount: "0",
                          cents: 0,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        netLiquidationValue: {
                          amount: "0",
                          cents: 0,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        withdrawals: {
                          amount: "0",
                          cents: 0,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        __typename: "CustodianAccountCurrentFinancialValues",
                      },
                      tradingBalance: [],
                      __typename: "CustodianAccountFinancialsSo",
                    },
                  },
                ],
                linkedAccount: null,
              },
              __typename: "AccountEdge",
            },
            {
              cursor: "Mg",
              node: {
                id: "tfsa-bwqflykd",
                applicationFamilyId:
                  "application_family-1xHC4nCktjP9Zfx95bcBPuUqyk",
                archivedAt: null,
                branch: "TR",
                category: "REGISTERED",
                closedAt: null,
                createdAt: "2020-03-20T22:56:32Z",
                currency: "CAD",
                requiredIdentityVerification: "fintracVerification",
                unifiedAccountType: "SELF_DIRECTED_TFSA",
                updatedAt: "2022-08-26T13:40:00Z",
                nickname: null,
                status: "open",
                accountOwnerConfiguration: null,
                accountFeatures: [
                  {
                    name: "OPTIONS_LEVEL_I",
                    enabled: true,
                    __typename: "AccountFeature",
                  },
                  {
                    name: "FULLY_PAID_LENDING",
                    enabled: false,
                    __typename: "AccountFeature",
                  },
                ],
                accountOwners: [
                  {
                    accountId: "tfsa-bwqflykd",
                    identityId: "identity-9ArKqNCmhnxU1sbZGd91BwDt8Wt",
                    accountNickname: null,
                    clientCanonicalId: "user-tsv6qxw1l8c",
                    accountOpeningAgreementsSigned: true,
                    name: " Li",
                    email: "ylilarry@gmail.com",
                    ownershipType: "primary",
                    activeInvitation: null,
                    __typename: "AccountOwner",
                  },
                ],
                type: "tfsa",
                __typename: "Account",
                custodianAccounts: [
                  {
                    id: "H242171K9CAD",
                    branch: "TR",
                    countryCode: "CA",
                    createdAt: "2020-03-20T22:56:33Z",
                    currency: "CAD",
                    custodian: "so",
                    status: "open",
                    updatedAt: "2023-11-11T14:41:22Z",
                    __typename: "CustodianAccount",
                    financials: {
                      current: {
                        deposits: {
                          amount: "35500.71",
                          cents: 3550071,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        earnings: {
                          amount: "1127.412557",
                          cents: 112741,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        netDeposits: {
                          amount: "35400.71",
                          cents: 3540071,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        netLiquidationValue: {
                          amount: "36528.122557",
                          cents: 3652812,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        withdrawals: {
                          amount: "100",
                          cents: 10000,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        __typename: "CustodianAccountCurrentFinancialValues",
                      },
                      tradingBalance: [
                        {
                          quantity: "460.91",
                          securityId: "sec-c-cad",
                          __typename: "Balance",
                        },
                        {
                          quantity: "0",
                          securityId: "sec-s-053be3c2edd342ef8a98b7ae5b55fc6c",
                          __typename: "Balance",
                        },
                        {
                          quantity: "0",
                          securityId: "sec-s-05f5cf57732e4c01af2411ece3bd5d6f",
                          __typename: "Balance",
                        },
                        {
                          quantity: "0",
                          securityId: "sec-s-11e95fe8275c4c73ad5904b90e113c8d",
                          __typename: "Balance",
                        },
                        {
                          quantity: "171",
                          securityId: "sec-s-149c99d5a49349b0984233cef4045380",
                          __typename: "Balance",
                        },
                        {
                          quantity: "0",
                          securityId: "sec-s-22197b664d4f49a9a3d9d3531aa71187",
                          __typename: "Balance",
                        },
                        {
                          quantity: "0",
                          securityId: "sec-s-28d30608fd92463a82a4cc20327d3fde",
                          __typename: "Balance",
                        },
                        {
                          quantity: "0",
                          securityId: "sec-s-29d3bc44d29a43c3969257102700c62f",
                          __typename: "Balance",
                        },
                        {
                          quantity: "0",
                          securityId: "sec-s-2b8037d841ef447b816289bcdd93ab53",
                          __typename: "Balance",
                        },
                        {
                          quantity: "50",
                          securityId: "sec-s-32b9c4d4070243f2b19ac096cbc355db",
                          __typename: "Balance",
                        },
                        {
                          quantity: "0",
                          securityId: "sec-s-32eb1c257ada47f9901fa0344c24aacc",
                          __typename: "Balance",
                        },
                        {
                          quantity: "633",
                          securityId: "sec-s-3cb94af08eb84ac1af22de7893fae07f",
                          __typename: "Balance",
                        },
                        {
                          quantity: "0",
                          securityId: "sec-s-413a3b941cca4038bcc3abf951b34124",
                          __typename: "Balance",
                        },
                        {
                          quantity: "0",
                          securityId: "sec-s-44a99653dab447b8bb2cc2975cd9dae1",
                          __typename: "Balance",
                        },
                        {
                          quantity: "0",
                          securityId: "sec-s-47d83dadf078408bb5a94b47ef6b5f26",
                          __typename: "Balance",
                        },
                        {
                          quantity: "0",
                          securityId: "sec-s-4b09daa0fb1b40aa81fb8000910c9413",
                          __typename: "Balance",
                        },
                        {
                          quantity: "0",
                          securityId: "sec-s-5924faf6ef86456c935be45da0fac0da",
                          __typename: "Balance",
                        },
                        {
                          quantity: "0",
                          securityId: "sec-s-5f9014efdf2743e5aefa15c985f80dbf",
                          __typename: "Balance",
                        },
                        {
                          quantity: "15",
                          securityId: "sec-s-61e44b8bdc95485b8496d0dfa9b45423",
                          __typename: "Balance",
                        },
                        {
                          quantity: "0",
                          securityId: "sec-s-62964d97a959454baf83f9bfcbfe09d3",
                          __typename: "Balance",
                        },
                        {
                          quantity: "0",
                          securityId: "sec-s-660d8eee57044191ba9a543fb371a7cd",
                          __typename: "Balance",
                        },
                        {
                          quantity: "0",
                          securityId: "sec-s-6a4ea895b0074a9ab39a9cd4ce07f2a5",
                          __typename: "Balance",
                        },
                        {
                          quantity: "0",
                          securityId: "sec-s-6d4722ada05c465bbb7079891c404a1b",
                          __typename: "Balance",
                        },
                        {
                          quantity: "64",
                          securityId: "sec-s-6f723012894448dca311d8a1710f82d6",
                          __typename: "Balance",
                        },
                        {
                          quantity: "0",
                          securityId: "sec-s-703a5163be4e4a96a99f62f0980fd570",
                          __typename: "Balance",
                        },
                        {
                          quantity: "0",
                          securityId: "sec-s-71e1d35b168e41e882bfa5c7e6b565f4",
                          __typename: "Balance",
                        },
                        {
                          quantity: "117.7519",
                          securityId: "sec-s-72aca418e7724cea8ade97b988bbce39",
                          __typename: "Balance",
                        },
                        {
                          quantity: "19",
                          securityId: "sec-s-7699771f31964338a7ae166954dac40c",
                          __typename: "Balance",
                        },
                        {
                          quantity: "0",
                          securityId: "sec-s-7a2734db0b01451d81daed178b2a2354",
                          __typename: "Balance",
                        },
                        {
                          quantity: "0",
                          securityId: "sec-s-80e44c3265094dbca11cea59ea7d0cca",
                          __typename: "Balance",
                        },
                        {
                          quantity: "0",
                          securityId: "sec-s-84194305fcc946618cc1632d1e6d6993",
                          __typename: "Balance",
                        },
                        {
                          quantity: "0",
                          securityId: "sec-s-85a0acea052c4682adc0fbf75a26ed1c",
                          __typename: "Balance",
                        },
                        {
                          quantity: "0",
                          securityId: "sec-s-8604b3b1beea4fc999475fac9e5e48d2",
                          __typename: "Balance",
                        },
                        {
                          quantity: "0",
                          securityId: "sec-s-86e98f15da84437ba5d4f3f462fae0f3",
                          __typename: "Balance",
                        },
                        {
                          quantity: "0",
                          securityId: "sec-s-8732804ff77c4d7ba615a08ac977af51",
                          __typename: "Balance",
                        },
                        {
                          quantity: "0",
                          securityId: "sec-s-8c577bbec6f944b19350fe1e3d2c5a0e",
                          __typename: "Balance",
                        },
                        {
                          quantity: "0",
                          securityId: "sec-s-8d8e8a728e7649e9946bf24a363dbf80",
                          __typename: "Balance",
                        },
                        {
                          quantity: "6",
                          securityId: "sec-s-8fdfe7070dc7455bbf3de10c5e1ff4f0",
                          __typename: "Balance",
                        },
                        {
                          quantity: "0",
                          securityId: "sec-s-96f6de8002cd4fe3a9fd4f2962edc436",
                          __typename: "Balance",
                        },
                        {
                          quantity: "0",
                          securityId: "sec-s-a0901e9ee4f84b80bd64a5632015a498",
                          __typename: "Balance",
                        },
                        {
                          quantity: "0",
                          securityId: "sec-s-a2203bfeb6b741eab53c8e39274ee1bd",
                          __typename: "Balance",
                        },
                        {
                          quantity: "0",
                          securityId: "sec-s-a313ea27e7844fb1baf156886a264f03",
                          __typename: "Balance",
                        },
                        {
                          quantity: "0",
                          securityId: "sec-s-a888030fec9e413aa1c71e86f7e09c7e",
                          __typename: "Balance",
                        },
                        {
                          quantity: "0",
                          securityId: "sec-s-aee2d0052b904ee5bb08bf2f4e9f4983",
                          __typename: "Balance",
                        },
                        {
                          quantity: "0",
                          securityId: "sec-s-b2a6ca7a27f247b39f3103c3c7fae1bc",
                          __typename: "Balance",
                        },
                        {
                          quantity: "0",
                          securityId: "sec-s-c148457960a14dacbb2b996d49811f2a",
                          __typename: "Balance",
                        },
                        {
                          quantity: "0",
                          securityId: "sec-s-c3c7b0025e354d6dacb3389061aaf490",
                          __typename: "Balance",
                        },
                        {
                          quantity: "0",
                          securityId: "sec-s-c40f8cc3ca124d9cafe22ef3023ddf4b",
                          __typename: "Balance",
                        },
                        {
                          quantity: "0",
                          securityId: "sec-s-c469ad43be18477ba44d65216f4ed0f9",
                          __typename: "Balance",
                        },
                        {
                          quantity: "0",
                          securityId: "sec-s-c54a6919bc044134ab0dce61a45c951e",
                          __typename: "Balance",
                        },
                        {
                          quantity: "0",
                          securityId: "sec-s-c6fdad5b60704b8b8fe16a35b440200d",
                          __typename: "Balance",
                        },
                        {
                          quantity: "0",
                          securityId: "sec-s-c8c7e87516f7470d8f266756b3093afc",
                          __typename: "Balance",
                        },
                        {
                          quantity: "23",
                          securityId: "sec-s-cdcb01f5b2b8430fa8aefad5ed5ff1c6",
                          __typename: "Balance",
                        },
                        {
                          quantity: "0",
                          securityId: "sec-s-d54ed49b6c4f4e3aa8cfe3b90a61f2a3",
                          __typename: "Balance",
                        },
                        {
                          quantity: "252",
                          securityId: "sec-s-d7b8ffa309d6495a9e7cc9cd6c4a843a",
                          __typename: "Balance",
                        },
                        {
                          quantity: "180",
                          securityId: "sec-s-d7f76e2f20914ee8a13b065827e31925",
                          __typename: "Balance",
                        },
                        {
                          quantity: "55",
                          securityId: "sec-s-dcbf498f9af443c086ff39814ce51c90",
                          __typename: "Balance",
                        },
                        {
                          quantity: "0",
                          securityId: "sec-s-e096d737d46149549e3ce06851df9800",
                          __typename: "Balance",
                        },
                        {
                          quantity: "26",
                          securityId: "sec-s-e287fa184fd14742a4fbbc1181afe7e2",
                          __typename: "Balance",
                        },
                        {
                          quantity: "79",
                          securityId: "sec-s-e97e4ddf97474ab08040c7e1ca2ab7fc",
                          __typename: "Balance",
                        },
                        {
                          quantity: "0",
                          securityId: "sec-s-f915ad7d1c54459bb0b079ad676425b3",
                          __typename: "Balance",
                        },
                        {
                          quantity: "27",
                          securityId: "sec-s-fc5a2d3d2ae540dd8a11655c698b7ac5",
                          __typename: "Balance",
                        },
                        {
                          quantity: "0",
                          securityId: "sec-s-fd83eb0e871946e99f41a2be6dfd6928",
                          __typename: "Balance",
                        },
                      ],
                      __typename: "CustodianAccountFinancialsSo",
                    },
                  },
                ],
                linkedAccount: {
                  id: "tfsa-tklmra-h",
                  applicationFamilyId:
                    "application_family-1xHC4nCktjP9Zfx95bcBPuUqyk",
                  archivedAt: null,
                  branch: "TR",
                  category: "REGISTERED",
                  closedAt: null,
                  createdAt: "2022-08-26T13:39:58Z",
                  currency: "USD",
                  requiredIdentityVerification: "fintracVerification",
                  unifiedAccountType: "SELF_DIRECTED_TFSA",
                  updatedAt: "2022-08-26T13:40:00Z",
                  nickname: null,
                  status: "open",
                  accountOwnerConfiguration: null,
                  accountFeatures: [
                    {
                      name: "OPTIONS_LEVEL_I",
                      enabled: true,
                      __typename: "AccountFeature",
                    },
                    {
                      name: "FULLY_PAID_LENDING",
                      enabled: false,
                      __typename: "AccountFeature",
                    },
                  ],
                  accountOwners: [
                    {
                      accountId: "tfsa-tklmra-h",
                      identityId: "identity-9ArKqNCmhnxU1sbZGd91BwDt8Wt",
                      accountNickname: null,
                      clientCanonicalId: "user-tsv6qxw1l8c",
                      accountOpeningAgreementsSigned: false,
                      name: " Li",
                      email: "ylilarry@gmail.com",
                      ownershipType: "primary",
                      activeInvitation: null,
                      __typename: "AccountOwner",
                    },
                  ],
                  type: "tfsa",
                  __typename: "Account",
                  custodianAccounts: [
                    {
                      id: "HQ4DPLZK8USD",
                      branch: "TR",
                      countryCode: "CA",
                      createdAt: "2022-08-26T13:39:58Z",
                      currency: "USD",
                      custodian: "so",
                      status: "open",
                      updatedAt: "2023-11-11T14:41:22Z",
                      __typename: "CustodianAccount",
                    },
                  ],
                },
              },
              __typename: "AccountEdge",
            },
            {
              cursor: "Mw",
              node: {
                id: "tfsa-8j2uupua",
                applicationFamilyId: null,
                archivedAt: "2023-09-09T16:55:08Z",
                branch: "WS",
                category: "REGISTERED",
                closedAt: "2023-09-09T16:55:08Z",
                createdAt: "2021-11-16T22:23:15Z",
                currency: "CAD",
                requiredIdentityVerification: "fintracVerification",
                unifiedAccountType: "MANAGED_TFSA",
                updatedAt: "2023-09-09T16:55:08Z",
                nickname: null,
                status: "closed",
                accountOwnerConfiguration: null,
                accountFeatures: [],
                accountOwners: [
                  {
                    accountId: "tfsa-8j2uupua",
                    identityId: "identity-9ArKqNCmhnxU1sbZGd91BwDt8Wt",
                    accountNickname: null,
                    clientCanonicalId: "user-fdyu4vuuyun",
                    accountOpeningAgreementsSigned: true,
                    name: " Li",
                    email: "ylilarry@gmail.com",
                    ownershipType: "primary",
                    activeInvitation: null,
                    __typename: "AccountOwner",
                  },
                ],
                type: "tfsa",
                __typename: "Account",
                custodianAccounts: [
                  {
                    id: "WK0P5XRK6CAD",
                    branch: "WS",
                    countryCode: "CA",
                    createdAt: "2021-11-16T22:23:15Z",
                    currency: "CAD",
                    custodian: "so",
                    status: "closed",
                    updatedAt: "2023-11-11T14:41:22Z",
                    __typename: "CustodianAccount",
                    financials: {
                      current: {
                        deposits: {
                          amount: "0",
                          cents: 0,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        earnings: {
                          amount: "0",
                          cents: 0,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        netDeposits: {
                          amount: "0",
                          cents: 0,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        netLiquidationValue: {
                          amount: "0",
                          cents: 0,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        withdrawals: {
                          amount: "0",
                          cents: 0,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        __typename: "CustodianAccountCurrentFinancialValues",
                      },
                      tradingBalance: [],
                      __typename: "CustodianAccountFinancialsSo",
                    },
                  },
                ],
                linkedAccount: null,
              },
              __typename: "AccountEdge",
            },
            {
              cursor: "NA",
              node: {
                id: "ca-cash-9iiaknpr",
                applicationFamilyId: null,
                archivedAt: "2023-09-09T16:54:23Z",
                branch: "WS",
                category: "NON_REGISTERED",
                closedAt: "2023-09-09T16:54:23Z",
                createdAt: "2022-08-17T01:25:03Z",
                currency: "CAD",
                requiredIdentityVerification: "fintracVerification",
                unifiedAccountType: "MANAGED_SAVE",
                updatedAt: "2023-09-09T16:54:23Z",
                nickname: null,
                status: "closed",
                accountOwnerConfiguration: null,
                accountFeatures: [],
                accountOwners: [
                  {
                    accountId: "ca-cash-9iiaknpr",
                    identityId: "identity-9ArKqNCmhnxU1sbZGd91BwDt8Wt",
                    accountNickname: null,
                    clientCanonicalId: "user-fdyu4vuuyun",
                    accountOpeningAgreementsSigned: true,
                    name: " Li",
                    email: "ylilarry@gmail.com",
                    ownershipType: "primary",
                    activeInvitation: null,
                    __typename: "AccountOwner",
                  },
                ],
                type: "ca_cash",
                __typename: "Account",
                custodianAccounts: [
                  {
                    id: "WK1216804CAD",
                    branch: "WS",
                    countryCode: "CA",
                    createdAt: "2022-08-17T01:25:03Z",
                    currency: "CAD",
                    custodian: "so",
                    status: "closed",
                    updatedAt: "2023-11-11T14:41:22Z",
                    __typename: "CustodianAccount",
                    financials: {
                      current: {
                        deposits: {
                          amount: "0",
                          cents: 0,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        earnings: {
                          amount: "0",
                          cents: 0,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        netDeposits: {
                          amount: "0",
                          cents: 0,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        netLiquidationValue: {
                          amount: "0",
                          cents: 0,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        withdrawals: {
                          amount: "0",
                          cents: 0,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        __typename: "CustodianAccountCurrentFinancialValues",
                      },
                      tradingBalance: [],
                      __typename: "CustodianAccountFinancialsSo",
                    },
                  },
                ],
                linkedAccount: null,
              },
              __typename: "AccountEdge",
            },
            {
              cursor: "NQ",
              node: {
                id: "ca-cash-rzaxdixx",
                applicationFamilyId: null,
                archivedAt: "2023-09-09T16:54:48Z",
                branch: "WS",
                category: "NON_REGISTERED",
                closedAt: "2023-09-09T16:54:48Z",
                createdAt: "2022-08-17T01:30:22Z",
                currency: "CAD",
                requiredIdentityVerification: "fintracVerification",
                unifiedAccountType: "MANAGED_SAVE",
                updatedAt: "2023-09-09T16:54:48Z",
                nickname: null,
                status: "closed",
                accountOwnerConfiguration: null,
                accountFeatures: [],
                accountOwners: [
                  {
                    accountId: "ca-cash-rzaxdixx",
                    identityId: "identity-9ArKqNCmhnxU1sbZGd91BwDt8Wt",
                    accountNickname: null,
                    clientCanonicalId: "user-fdyu4vuuyun",
                    accountOpeningAgreementsSigned: true,
                    name: " Li",
                    email: "ylilarry@gmail.com",
                    ownershipType: "primary",
                    activeInvitation: null,
                    __typename: "AccountOwner",
                  },
                ],
                type: "ca_cash",
                __typename: "Account",
                custodianAccounts: [
                  {
                    id: "WK1216G05CAD",
                    branch: "WS",
                    countryCode: "CA",
                    createdAt: "2022-08-17T01:30:22Z",
                    currency: "CAD",
                    custodian: "so",
                    status: "closed",
                    updatedAt: "2023-11-11T14:41:22Z",
                    __typename: "CustodianAccount",
                    financials: {
                      current: {
                        deposits: {
                          amount: "0",
                          cents: 0,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        earnings: {
                          amount: "0",
                          cents: 0,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        netDeposits: {
                          amount: "0",
                          cents: 0,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        netLiquidationValue: {
                          amount: "0",
                          cents: 0,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        withdrawals: {
                          amount: "0",
                          cents: 0,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        __typename: "CustodianAccountCurrentFinancialValues",
                      },
                      tradingBalance: [],
                      __typename: "CustodianAccountFinancialsSo",
                    },
                  },
                ],
                linkedAccount: null,
              },
              __typename: "AccountEdge",
            },
            {
              cursor: "Ng",
              node: {
                id: "ca-cash-kqrw1syr",
                applicationFamilyId: null,
                archivedAt: "2023-09-09T16:54:33Z",
                branch: "WS",
                category: "NON_REGISTERED",
                closedAt: "2023-09-09T16:54:33Z",
                createdAt: "2022-08-17T05:25:26Z",
                currency: "CAD",
                requiredIdentityVerification: "fintracVerification",
                unifiedAccountType: "MANAGED_SAVE",
                updatedAt: "2023-09-09T16:54:33Z",
                nickname: null,
                status: "closed",
                accountOwnerConfiguration: null,
                accountFeatures: [],
                accountOwners: [
                  {
                    accountId: "ca-cash-kqrw1syr",
                    identityId: "identity-9ArKqNCmhnxU1sbZGd91BwDt8Wt",
                    accountNickname: null,
                    clientCanonicalId: "user-fdyu4vuuyun",
                    accountOpeningAgreementsSigned: false,
                    name: " Li",
                    email: "ylilarry@gmail.com",
                    ownershipType: "primary",
                    activeInvitation: null,
                    __typename: "AccountOwner",
                  },
                ],
                type: "ca_cash",
                __typename: "Account",
                custodianAccounts: [
                  {
                    id: "WK121FC09CAD",
                    branch: "WS",
                    countryCode: "CA",
                    createdAt: "2022-08-17T05:25:26Z",
                    currency: "CAD",
                    custodian: "so",
                    status: "closed",
                    updatedAt: "2023-11-11T14:41:22Z",
                    __typename: "CustodianAccount",
                    financials: {
                      current: {
                        deposits: {
                          amount: "0",
                          cents: 0,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        earnings: {
                          amount: "0",
                          cents: 0,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        netDeposits: {
                          amount: "0",
                          cents: 0,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        netLiquidationValue: {
                          amount: "0",
                          cents: 0,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        withdrawals: {
                          amount: "0",
                          cents: 0,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        __typename: "CustodianAccountCurrentFinancialValues",
                      },
                      tradingBalance: [],
                      __typename: "CustodianAccountFinancialsSo",
                    },
                  },
                ],
                linkedAccount: null,
              },
              __typename: "AccountEdge",
            },
            {
              cursor: "Nw",
              node: {
                id: "tfsa-tklmra-h",
                applicationFamilyId:
                  "application_family-1xHC4nCktjP9Zfx95bcBPuUqyk",
                archivedAt: null,
                branch: "TR",
                category: "REGISTERED",
                closedAt: null,
                createdAt: "2022-08-26T13:39:58Z",
                currency: "USD",
                requiredIdentityVerification: "fintracVerification",
                unifiedAccountType: "SELF_DIRECTED_TFSA",
                updatedAt: "2022-08-26T13:40:00Z",
                nickname: null,
                status: "open",
                accountOwnerConfiguration: null,
                accountFeatures: [
                  {
                    name: "OPTIONS_LEVEL_I",
                    enabled: true,
                    __typename: "AccountFeature",
                  },
                  {
                    name: "FULLY_PAID_LENDING",
                    enabled: false,
                    __typename: "AccountFeature",
                  },
                ],
                accountOwners: [
                  {
                    accountId: "tfsa-tklmra-h",
                    identityId: "identity-9ArKqNCmhnxU1sbZGd91BwDt8Wt",
                    accountNickname: null,
                    clientCanonicalId: "user-tsv6qxw1l8c",
                    accountOpeningAgreementsSigned: false,
                    name: " Li",
                    email: "ylilarry@gmail.com",
                    ownershipType: "primary",
                    activeInvitation: null,
                    __typename: "AccountOwner",
                  },
                ],
                type: "tfsa",
                __typename: "Account",
                custodianAccounts: [
                  {
                    id: "HQ4DPLZK8USD",
                    branch: "TR",
                    countryCode: "CA",
                    createdAt: "2022-08-26T13:39:58Z",
                    currency: "USD",
                    custodian: "so",
                    status: "open",
                    updatedAt: "2023-11-11T14:41:22Z",
                    __typename: "CustodianAccount",
                    financials: {
                      current: {
                        deposits: {
                          amount: "75.59",
                          cents: 7559,
                          currency: "USD",
                          __typename: "Money",
                        },
                        earnings: {
                          amount: "0",
                          cents: 0,
                          currency: "USD",
                          __typename: "Money",
                        },
                        netDeposits: {
                          amount: "0",
                          cents: 0,
                          currency: "USD",
                          __typename: "Money",
                        },
                        netLiquidationValue: {
                          amount: "0",
                          cents: 0,
                          currency: "USD",
                          __typename: "Money",
                        },
                        withdrawals: {
                          amount: "75.59",
                          cents: 7559,
                          currency: "USD",
                          __typename: "Money",
                        },
                        __typename: "CustodianAccountCurrentFinancialValues",
                      },
                      tradingBalance: [
                        {
                          quantity: "0",
                          securityId: "sec-c-usd",
                          __typename: "Balance",
                        },
                      ],
                      __typename: "CustodianAccountFinancialsSo",
                    },
                  },
                ],
                linkedAccount: {
                  id: "tfsa-bwqflykd",
                  applicationFamilyId:
                    "application_family-1xHC4nCktjP9Zfx95bcBPuUqyk",
                  archivedAt: null,
                  branch: "TR",
                  category: "REGISTERED",
                  closedAt: null,
                  createdAt: "2020-03-20T22:56:32Z",
                  currency: "CAD",
                  requiredIdentityVerification: "fintracVerification",
                  unifiedAccountType: "SELF_DIRECTED_TFSA",
                  updatedAt: "2022-08-26T13:40:00Z",
                  nickname: null,
                  status: "open",
                  accountOwnerConfiguration: null,
                  accountFeatures: [
                    {
                      name: "OPTIONS_LEVEL_I",
                      enabled: true,
                      __typename: "AccountFeature",
                    },
                    {
                      name: "FULLY_PAID_LENDING",
                      enabled: false,
                      __typename: "AccountFeature",
                    },
                  ],
                  accountOwners: [
                    {
                      accountId: "tfsa-bwqflykd",
                      identityId: "identity-9ArKqNCmhnxU1sbZGd91BwDt8Wt",
                      accountNickname: null,
                      clientCanonicalId: "user-tsv6qxw1l8c",
                      accountOpeningAgreementsSigned: true,
                      name: " Li",
                      email: "ylilarry@gmail.com",
                      ownershipType: "primary",
                      activeInvitation: null,
                      __typename: "AccountOwner",
                    },
                  ],
                  type: "tfsa",
                  __typename: "Account",
                  custodianAccounts: [
                    {
                      id: "H242171K9CAD",
                      branch: "TR",
                      countryCode: "CA",
                      createdAt: "2020-03-20T22:56:33Z",
                      currency: "CAD",
                      custodian: "so",
                      status: "open",
                      updatedAt: "2023-11-11T14:41:22Z",
                      __typename: "CustodianAccount",
                    },
                  ],
                },
              },
              __typename: "AccountEdge",
            },
            {
              cursor: "OA",
              node: {
                id: "non-registered-72inhspu",
                applicationFamilyId:
                  "application_family-1xHC4nCktjP9Zfx95bcBPuUqyk",
                archivedAt: "2023-09-09T16:55:19Z",
                branch: "TR",
                category: "NON_REGISTERED",
                closedAt: "2023-09-09T16:55:19Z",
                createdAt: "2022-08-26T13:39:59Z",
                currency: "USD",
                requiredIdentityVerification: "fintracVerification",
                unifiedAccountType: "SELF_DIRECTED_NON_REGISTERED",
                updatedAt: "2023-09-09T16:55:34Z",
                nickname: null,
                status: "closed",
                accountOwnerConfiguration: null,
                accountFeatures: [
                  {
                    name: "FULLY_PAID_LENDING",
                    enabled: true,
                    __typename: "AccountFeature",
                  },
                ],
                accountOwners: [
                  {
                    accountId: "non-registered-72inhspu",
                    identityId: "identity-9ArKqNCmhnxU1sbZGd91BwDt8Wt",
                    accountNickname: null,
                    clientCanonicalId: "user-tsv6qxw1l8c",
                    accountOpeningAgreementsSigned: false,
                    name: " Li",
                    email: "ylilarry@gmail.com",
                    ownershipType: "primary",
                    activeInvitation: null,
                    __typename: "AccountOwner",
                  },
                ],
                type: "non_registered",
                __typename: "Account",
                custodianAccounts: [
                  {
                    id: "HQ4DPM008USD",
                    branch: "TR",
                    countryCode: "CA",
                    createdAt: "2022-08-26T13:40:00Z",
                    currency: "USD",
                    custodian: "so",
                    status: "closed",
                    updatedAt: "2023-11-11T14:41:22Z",
                    __typename: "CustodianAccount",
                    financials: {
                      current: {
                        deposits: {
                          amount: "0",
                          cents: 0,
                          currency: "USD",
                          __typename: "Money",
                        },
                        earnings: {
                          amount: "0",
                          cents: 0,
                          currency: "USD",
                          __typename: "Money",
                        },
                        netDeposits: {
                          amount: "0",
                          cents: 0,
                          currency: "USD",
                          __typename: "Money",
                        },
                        netLiquidationValue: {
                          amount: "0",
                          cents: 0,
                          currency: "USD",
                          __typename: "Money",
                        },
                        withdrawals: {
                          amount: "0",
                          cents: 0,
                          currency: "USD",
                          __typename: "Money",
                        },
                        __typename: "CustodianAccountCurrentFinancialValues",
                      },
                      tradingBalance: [],
                      __typename: "CustodianAccountFinancialsSo",
                    },
                  },
                ],
                linkedAccount: null,
              },
              __typename: "AccountEdge",
            },
            {
              cursor: "OQ",
              node: {
                id: "ca-cash-msb-osjeojA2dw",
                applicationFamilyId: null,
                archivedAt: null,
                branch: "WS",
                category: "NON_REGISTERED",
                closedAt: null,
                createdAt: "2023-09-09T16:49:57Z",
                currency: "CAD",
                requiredIdentityVerification: "fintracVerification",
                unifiedAccountType: "CASH",
                updatedAt: "2023-09-09T16:49:57Z",
                nickname: null,
                status: "open",
                accountOwnerConfiguration: null,
                accountFeatures: [
                  {
                    name: "WALLET",
                    enabled: true,
                    __typename: "AccountFeature",
                  },
                ],
                accountOwners: [
                  {
                    accountId: "ca-cash-msb-osjeojA2dw",
                    identityId: "identity-9ArKqNCmhnxU1sbZGd91BwDt8Wt",
                    accountNickname: null,
                    clientCanonicalId: "user-fdyu4vuuyun",
                    accountOpeningAgreementsSigned: true,
                    name: " Li",
                    email: "ylilarry@gmail.com",
                    ownershipType: "primary",
                    activeInvitation: null,
                    __typename: "AccountOwner",
                  },
                ],
                type: "ca_cash_msb",
                __typename: "Account",
                custodianAccounts: [
                  {
                    id: "C11594527CAD",
                    branch: "CH",
                    countryCode: "CA",
                    createdAt: "2023-09-09T16:49:58Z",
                    currency: "CAD",
                    custodian: "so",
                    status: "open",
                    updatedAt: "2023-09-09T16:50:12Z",
                    __typename: "CustodianAccount",
                    financials: {
                      current: {
                        deposits: {
                          amount: "0",
                          cents: 0,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        earnings: {
                          amount: "0",
                          cents: 0,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        netDeposits: {
                          amount: "0",
                          cents: 0,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        netLiquidationValue: {
                          amount: "0",
                          cents: 0,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        withdrawals: {
                          amount: "0",
                          cents: 0,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        __typename: "CustodianAccountCurrentFinancialValues",
                      },
                      tradingBalance: [],
                      __typename: "CustodianAccountFinancialsSo",
                    },
                  },
                  {
                    id: "WK228MF37CAD",
                    branch: "WS",
                    countryCode: "CA",
                    createdAt: "2023-09-09T16:59:18Z",
                    currency: "CAD",
                    custodian: "so",
                    status: "open",
                    updatedAt: "2023-11-11T14:41:22Z",
                    __typename: "CustodianAccount",
                    financials: {
                      current: {
                        deposits: {
                          amount: "0",
                          cents: 0,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        earnings: {
                          amount: "0",
                          cents: 0,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        netDeposits: {
                          amount: "0",
                          cents: 0,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        netLiquidationValue: {
                          amount: "0",
                          cents: 0,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        withdrawals: {
                          amount: "0",
                          cents: 0,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        __typename: "CustodianAccountCurrentFinancialValues",
                      },
                      tradingBalance: [],
                      __typename: "CustodianAccountFinancialsSo",
                    },
                  },
                ],
                linkedAccount: null,
              },
              __typename: "AccountEdge",
            },
            {
              cursor: "MTA",
              node: {
                id: "non-registered-c9SlDnPRDw",
                applicationFamilyId:
                  "application_family-1xHC4nCktjP9Zfx95bcBPuUqyk",
                archivedAt: null,
                branch: "TR",
                category: "NON_REGISTERED",
                closedAt: null,
                createdAt: "2023-10-11T20:48:46Z",
                currency: "CAD",
                requiredIdentityVerification: "fintracVerification",
                unifiedAccountType: "SELF_DIRECTED_NON_REGISTERED",
                updatedAt: "2023-10-11T20:48:48Z",
                nickname: null,
                status: "open",
                accountOwnerConfiguration: null,
                accountFeatures: [
                  {
                    name: "FULLY_PAID_LENDING",
                    enabled: false,
                    __typename: "AccountFeature",
                  },
                ],
                accountOwners: [
                  {
                    accountId: "non-registered-c9SlDnPRDw",
                    identityId: "identity-9ArKqNCmhnxU1sbZGd91BwDt8Wt",
                    accountNickname: null,
                    clientCanonicalId: "user-tsv6qxw1l8c",
                    accountOpeningAgreementsSigned: true,
                    name: " Li",
                    email: "ylilarry@gmail.com",
                    ownershipType: "primary",
                    activeInvitation: null,
                    __typename: "AccountOwner",
                  },
                ],
                type: "non_registered",
                __typename: "Account",
                custodianAccounts: [
                  {
                    id: "HQ59MHQ02CAD",
                    branch: "TR",
                    countryCode: "CA",
                    createdAt: "2023-10-11T20:48:47Z",
                    currency: "CAD",
                    custodian: "so",
                    status: "open",
                    updatedAt: "2023-11-11T14:41:22Z",
                    __typename: "CustodianAccount",
                    financials: {
                      current: {
                        deposits: {
                          amount: "5000",
                          cents: 500000,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        earnings: {
                          amount: "-70.625",
                          cents: -7063,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        netDeposits: {
                          amount: "5000",
                          cents: 500000,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        netLiquidationValue: {
                          amount: "4929.375",
                          cents: 492938,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        withdrawals: {
                          amount: "0",
                          cents: 0,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        __typename: "CustodianAccountCurrentFinancialValues",
                      },
                      tradingBalance: [
                        {
                          quantity: "41.72",
                          securityId: "sec-c-cad",
                          __typename: "Balance",
                        },
                        {
                          quantity: "0",
                          securityId: "sec-s-62964d97a959454baf83f9bfcbfe09d3",
                          __typename: "Balance",
                        },
                        {
                          quantity: "69",
                          securityId: "sec-s-6d4722ada05c465bbb7079891c404a1b",
                          __typename: "Balance",
                        },
                        {
                          quantity: "77",
                          securityId: "sec-s-72aca418e7724cea8ade97b988bbce39",
                          __typename: "Balance",
                        },
                        {
                          quantity: "0",
                          securityId: "sec-s-c40f8cc3ca124d9cafe22ef3023ddf4b",
                          __typename: "Balance",
                        },
                      ],
                      __typename: "CustodianAccountFinancialsSo",
                    },
                  },
                ],
                linkedAccount: {
                  id: "non-registered-DmSK3I1BfA",
                  applicationFamilyId:
                    "application_family-1xHC4nCktjP9Zfx95bcBPuUqyk",
                  archivedAt: null,
                  branch: "TR",
                  category: "NON_REGISTERED",
                  closedAt: null,
                  createdAt: "2023-10-11T20:48:47Z",
                  currency: "USD",
                  requiredIdentityVerification: "fintracVerification",
                  unifiedAccountType: "SELF_DIRECTED_NON_REGISTERED",
                  updatedAt: "2023-10-11T20:48:47Z",
                  nickname: null,
                  status: "open",
                  accountOwnerConfiguration: null,
                  accountFeatures: [
                    {
                      name: "FULLY_PAID_LENDING",
                      enabled: false,
                      __typename: "AccountFeature",
                    },
                  ],
                  accountOwners: [
                    {
                      accountId: "non-registered-DmSK3I1BfA",
                      identityId: "identity-9ArKqNCmhnxU1sbZGd91BwDt8Wt",
                      accountNickname: null,
                      clientCanonicalId: "user-tsv6qxw1l8c",
                      accountOpeningAgreementsSigned: false,
                      name: " Li",
                      email: "ylilarry@gmail.com",
                      ownershipType: "primary",
                      activeInvitation: null,
                      __typename: "AccountOwner",
                    },
                  ],
                  type: "non_registered",
                  __typename: "Account",
                  custodianAccounts: [
                    {
                      id: "HQ59MHR01USD",
                      branch: "TR",
                      countryCode: "CA",
                      createdAt: "2023-10-11T20:48:48Z",
                      currency: "USD",
                      custodian: "so",
                      status: "open",
                      updatedAt: "2023-11-11T14:41:22Z",
                      __typename: "CustodianAccount",
                    },
                  ],
                },
              },
              __typename: "AccountEdge",
            },
            {
              cursor: "MTE",
              node: {
                id: "non-registered-DmSK3I1BfA",
                applicationFamilyId:
                  "application_family-1xHC4nCktjP9Zfx95bcBPuUqyk",
                archivedAt: null,
                branch: "TR",
                category: "NON_REGISTERED",
                closedAt: null,
                createdAt: "2023-10-11T20:48:47Z",
                currency: "USD",
                requiredIdentityVerification: "fintracVerification",
                unifiedAccountType: "SELF_DIRECTED_NON_REGISTERED",
                updatedAt: "2023-10-11T20:48:47Z",
                nickname: null,
                status: "open",
                accountOwnerConfiguration: null,
                accountFeatures: [
                  {
                    name: "FULLY_PAID_LENDING",
                    enabled: false,
                    __typename: "AccountFeature",
                  },
                ],
                accountOwners: [
                  {
                    accountId: "non-registered-DmSK3I1BfA",
                    identityId: "identity-9ArKqNCmhnxU1sbZGd91BwDt8Wt",
                    accountNickname: null,
                    clientCanonicalId: "user-tsv6qxw1l8c",
                    accountOpeningAgreementsSigned: false,
                    name: " Li",
                    email: "ylilarry@gmail.com",
                    ownershipType: "primary",
                    activeInvitation: null,
                    __typename: "AccountOwner",
                  },
                ],
                type: "non_registered",
                __typename: "Account",
                custodianAccounts: [
                  {
                    id: "HQ59MHR01USD",
                    branch: "TR",
                    countryCode: "CA",
                    createdAt: "2023-10-11T20:48:48Z",
                    currency: "USD",
                    custodian: "so",
                    status: "open",
                    updatedAt: "2023-11-11T14:41:22Z",
                    __typename: "CustodianAccount",
                    financials: {
                      current: {
                        deposits: {
                          amount: "0",
                          cents: 0,
                          currency: "USD",
                          __typename: "Money",
                        },
                        earnings: {
                          amount: "0",
                          cents: 0,
                          currency: "USD",
                          __typename: "Money",
                        },
                        netDeposits: {
                          amount: "0",
                          cents: 0,
                          currency: "USD",
                          __typename: "Money",
                        },
                        netLiquidationValue: {
                          amount: "0",
                          cents: 0,
                          currency: "USD",
                          __typename: "Money",
                        },
                        withdrawals: {
                          amount: "0",
                          cents: 0,
                          currency: "USD",
                          __typename: "Money",
                        },
                        __typename: "CustodianAccountCurrentFinancialValues",
                      },
                      tradingBalance: [],
                      __typename: "CustodianAccountFinancialsSo",
                    },
                  },
                ],
                linkedAccount: {
                  id: "non-registered-c9SlDnPRDw",
                  applicationFamilyId:
                    "application_family-1xHC4nCktjP9Zfx95bcBPuUqyk",
                  archivedAt: null,
                  branch: "TR",
                  category: "NON_REGISTERED",
                  closedAt: null,
                  createdAt: "2023-10-11T20:48:46Z",
                  currency: "CAD",
                  requiredIdentityVerification: "fintracVerification",
                  unifiedAccountType: "SELF_DIRECTED_NON_REGISTERED",
                  updatedAt: "2023-10-11T20:48:48Z",
                  nickname: null,
                  status: "open",
                  accountOwnerConfiguration: null,
                  accountFeatures: [
                    {
                      name: "FULLY_PAID_LENDING",
                      enabled: false,
                      __typename: "AccountFeature",
                    },
                  ],
                  accountOwners: [
                    {
                      accountId: "non-registered-c9SlDnPRDw",
                      identityId: "identity-9ArKqNCmhnxU1sbZGd91BwDt8Wt",
                      accountNickname: null,
                      clientCanonicalId: "user-tsv6qxw1l8c",
                      accountOpeningAgreementsSigned: true,
                      name: " Li",
                      email: "ylilarry@gmail.com",
                      ownershipType: "primary",
                      activeInvitation: null,
                      __typename: "AccountOwner",
                    },
                  ],
                  type: "non_registered",
                  __typename: "Account",
                  custodianAccounts: [
                    {
                      id: "HQ59MHQ02CAD",
                      branch: "TR",
                      countryCode: "CA",
                      createdAt: "2023-10-11T20:48:47Z",
                      currency: "CAD",
                      custodian: "so",
                      status: "open",
                      updatedAt: "2023-11-11T14:41:22Z",
                      __typename: "CustodianAccount",
                    },
                  ],
                },
              },
              __typename: "AccountEdge",
            },
            {
              cursor: "MTI",
              node: {
                id: "rrsp-z-rbIVVndQ",
                applicationFamilyId:
                  "application_family-1xHC4nCktjP9Zfx95bcBPuUqyk",
                archivedAt: null,
                branch: "TR",
                category: "REGISTERED",
                closedAt: null,
                createdAt: "2023-10-19T06:37:15Z",
                currency: "CAD",
                requiredIdentityVerification: "fintracVerification",
                unifiedAccountType: "SELF_DIRECTED_RRSP",
                updatedAt: "2023-10-19T06:37:17Z",
                nickname: null,
                status: "open",
                accountOwnerConfiguration: null,
                accountFeatures: [],
                accountOwners: [
                  {
                    accountId: "rrsp-z-rbIVVndQ",
                    identityId: "identity-9ArKqNCmhnxU1sbZGd91BwDt8Wt",
                    accountNickname: null,
                    clientCanonicalId: "user-tsv6qxw1l8c",
                    accountOpeningAgreementsSigned: true,
                    name: " Li",
                    email: "ylilarry@gmail.com",
                    ownershipType: "primary",
                    activeInvitation: null,
                    __typename: "AccountOwner",
                  },
                ],
                type: "rrsp",
                __typename: "Account",
                custodianAccounts: [
                  {
                    id: "HQ5B4Q740CAD",
                    branch: "TR",
                    countryCode: "CA",
                    createdAt: "2023-10-19T06:37:16Z",
                    currency: "CAD",
                    custodian: "so",
                    status: "open",
                    updatedAt: "2023-11-11T14:41:22Z",
                    __typename: "CustodianAccount",
                    financials: {
                      current: {
                        deposits: {
                          amount: "10000",
                          cents: 1000000,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        earnings: {
                          amount: "421.395164",
                          cents: 42140,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        netDeposits: {
                          amount: "10000",
                          cents: 1000000,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        netLiquidationValue: {
                          amount: "10421.395164",
                          cents: 1042140,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        withdrawals: {
                          amount: "0",
                          cents: 0,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        __typename: "CustodianAccountCurrentFinancialValues",
                      },
                      tradingBalance: [
                        {
                          quantity: "23.22",
                          securityId: "sec-c-cad",
                          __typename: "Balance",
                        },
                        {
                          quantity: "0",
                          securityId: "sec-s-6a4ea895b0074a9ab39a9cd4ce07f2a5",
                          __typename: "Balance",
                        },
                        {
                          quantity: "207.8388",
                          securityId: "sec-s-72aca418e7724cea8ade97b988bbce39",
                          __typename: "Balance",
                        },
                        {
                          quantity: "0",
                          securityId: "sec-s-86e98f15da84437ba5d4f3f462fae0f3",
                          __typename: "Balance",
                        },
                        {
                          quantity: "0",
                          securityId: "sec-s-8fdfe7070dc7455bbf3de10c5e1ff4f0",
                          __typename: "Balance",
                        },
                        {
                          quantity: "0",
                          securityId: "sec-s-d7f76e2f20914ee8a13b065827e31925",
                          __typename: "Balance",
                        },
                        {
                          quantity: "0",
                          securityId: "sec-s-fd83eb0e871946e99f41a2be6dfd6928",
                          __typename: "Balance",
                        },
                      ],
                      __typename: "CustodianAccountFinancialsSo",
                    },
                  },
                ],
                linkedAccount: {
                  id: "rrsp-I1ExpalUug",
                  applicationFamilyId:
                    "application_family-1xHC4nCktjP9Zfx95bcBPuUqyk",
                  archivedAt: null,
                  branch: "TR",
                  category: "REGISTERED",
                  closedAt: null,
                  createdAt: "2023-10-19T06:37:16Z",
                  currency: "USD",
                  requiredIdentityVerification: "fintracVerification",
                  unifiedAccountType: "SELF_DIRECTED_RRSP",
                  updatedAt: "2023-10-19T06:37:16Z",
                  nickname: null,
                  status: "open",
                  accountOwnerConfiguration: null,
                  accountFeatures: [],
                  accountOwners: [
                    {
                      accountId: "rrsp-I1ExpalUug",
                      identityId: "identity-9ArKqNCmhnxU1sbZGd91BwDt8Wt",
                      accountNickname: null,
                      clientCanonicalId: "user-tsv6qxw1l8c",
                      accountOpeningAgreementsSigned: false,
                      name: " Li",
                      email: "ylilarry@gmail.com",
                      ownershipType: "primary",
                      activeInvitation: null,
                      __typename: "AccountOwner",
                    },
                  ],
                  type: "rrsp",
                  __typename: "Account",
                  custodianAccounts: [
                    {
                      id: "HQ5B4Q849USD",
                      branch: "TR",
                      countryCode: "CA",
                      createdAt: "2023-10-19T06:37:16Z",
                      currency: "USD",
                      custodian: "so",
                      status: "open",
                      updatedAt: "2023-11-11T14:41:22Z",
                      __typename: "CustodianAccount",
                    },
                  ],
                },
              },
              __typename: "AccountEdge",
            },
            {
              cursor: "MTM",
              node: {
                id: "rrsp-I1ExpalUug",
                applicationFamilyId:
                  "application_family-1xHC4nCktjP9Zfx95bcBPuUqyk",
                archivedAt: null,
                branch: "TR",
                category: "REGISTERED",
                closedAt: null,
                createdAt: "2023-10-19T06:37:16Z",
                currency: "USD",
                requiredIdentityVerification: "fintracVerification",
                unifiedAccountType: "SELF_DIRECTED_RRSP",
                updatedAt: "2023-10-19T06:37:16Z",
                nickname: null,
                status: "open",
                accountOwnerConfiguration: null,
                accountFeatures: [],
                accountOwners: [
                  {
                    accountId: "rrsp-I1ExpalUug",
                    identityId: "identity-9ArKqNCmhnxU1sbZGd91BwDt8Wt",
                    accountNickname: null,
                    clientCanonicalId: "user-tsv6qxw1l8c",
                    accountOpeningAgreementsSigned: false,
                    name: " Li",
                    email: "ylilarry@gmail.com",
                    ownershipType: "primary",
                    activeInvitation: null,
                    __typename: "AccountOwner",
                  },
                ],
                type: "rrsp",
                __typename: "Account",
                custodianAccounts: [
                  {
                    id: "HQ5B4Q849USD",
                    branch: "TR",
                    countryCode: "CA",
                    createdAt: "2023-10-19T06:37:16Z",
                    currency: "USD",
                    custodian: "so",
                    status: "open",
                    updatedAt: "2023-11-11T14:41:22Z",
                    __typename: "CustodianAccount",
                    financials: {
                      current: {
                        deposits: {
                          amount: "0",
                          cents: 0,
                          currency: "USD",
                          __typename: "Money",
                        },
                        earnings: {
                          amount: "0",
                          cents: 0,
                          currency: "USD",
                          __typename: "Money",
                        },
                        netDeposits: {
                          amount: "0",
                          cents: 0,
                          currency: "USD",
                          __typename: "Money",
                        },
                        netLiquidationValue: {
                          amount: "0",
                          cents: 0,
                          currency: "USD",
                          __typename: "Money",
                        },
                        withdrawals: {
                          amount: "0",
                          cents: 0,
                          currency: "USD",
                          __typename: "Money",
                        },
                        __typename: "CustodianAccountCurrentFinancialValues",
                      },
                      tradingBalance: [],
                      __typename: "CustodianAccountFinancialsSo",
                    },
                  },
                ],
                linkedAccount: {
                  id: "rrsp-z-rbIVVndQ",
                  applicationFamilyId:
                    "application_family-1xHC4nCktjP9Zfx95bcBPuUqyk",
                  archivedAt: null,
                  branch: "TR",
                  category: "REGISTERED",
                  closedAt: null,
                  createdAt: "2023-10-19T06:37:15Z",
                  currency: "CAD",
                  requiredIdentityVerification: "fintracVerification",
                  unifiedAccountType: "SELF_DIRECTED_RRSP",
                  updatedAt: "2023-10-19T06:37:17Z",
                  nickname: null,
                  status: "open",
                  accountOwnerConfiguration: null,
                  accountFeatures: [],
                  accountOwners: [
                    {
                      accountId: "rrsp-z-rbIVVndQ",
                      identityId: "identity-9ArKqNCmhnxU1sbZGd91BwDt8Wt",
                      accountNickname: null,
                      clientCanonicalId: "user-tsv6qxw1l8c",
                      accountOpeningAgreementsSigned: true,
                      name: " Li",
                      email: "ylilarry@gmail.com",
                      ownershipType: "primary",
                      activeInvitation: null,
                      __typename: "AccountOwner",
                    },
                  ],
                  type: "rrsp",
                  __typename: "Account",
                  custodianAccounts: [
                    {
                      id: "HQ5B4Q740CAD",
                      branch: "TR",
                      countryCode: "CA",
                      createdAt: "2023-10-19T06:37:16Z",
                      currency: "CAD",
                      custodian: "so",
                      status: "open",
                      updatedAt: "2023-11-11T14:41:22Z",
                      __typename: "CustodianAccount",
                    },
                  ],
                },
              },
              __typename: "AccountEdge",
            },
            {
              cursor: "MTQ",
              node: {
                id: "non-registered-crypto-t0SUJ7520w",
                applicationFamilyId:
                  "application_family-1xHC4nCktjP9Zfx95bcBPuUqyk",
                archivedAt: "2023-11-24T16:20:19Z",
                branch: "TR",
                category: "NON_REGISTERED",
                closedAt: "2023-11-24T16:20:19Z",
                createdAt: "2023-11-09T02:03:11Z",
                currency: "CAD",
                requiredIdentityVerification: "fintracVerification",
                unifiedAccountType: "SELF_DIRECTED_CRYPTO",
                updatedAt: "2023-11-24T16:20:19Z",
                nickname: null,
                status: "closed",
                accountOwnerConfiguration: null,
                accountFeatures: [],
                accountOwners: [
                  {
                    accountId: "non-registered-crypto-t0SUJ7520w",
                    identityId: "identity-9ArKqNCmhnxU1sbZGd91BwDt8Wt",
                    accountNickname: null,
                    clientCanonicalId: "user-tsv6qxw1l8c",
                    accountOpeningAgreementsSigned: false,
                    name: " Li",
                    email: "ylilarry@gmail.com",
                    ownershipType: "primary",
                    activeInvitation: null,
                    __typename: "AccountOwner",
                  },
                ],
                type: "non_registered_crypto",
                __typename: "Account",
                custodianAccounts: [
                  {
                    id: "HQ5CT5V16CAD",
                    branch: "TR",
                    countryCode: "CA",
                    createdAt: "2023-11-09T02:03:11Z",
                    currency: "CAD",
                    custodian: "so",
                    status: "closed",
                    updatedAt: "2023-11-24T16:20:24Z",
                    __typename: "CustodianAccount",
                    financials: {
                      current: {
                        deposits: {
                          amount: "0",
                          cents: 0,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        earnings: {
                          amount: "0",
                          cents: 0,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        netDeposits: {
                          amount: "0",
                          cents: 0,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        netLiquidationValue: {
                          amount: "0",
                          cents: 0,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        withdrawals: {
                          amount: "0",
                          cents: 0,
                          currency: "CAD",
                          __typename: "Money",
                        },
                        __typename: "CustodianAccountCurrentFinancialValues",
                      },
                      tradingBalance: [],
                      __typename: "CustodianAccountFinancialsSo",
                    },
                  },
                ],
                linkedAccount: null,
              },
              __typename: "AccountEdge",
            },
            {
              cursor: "MTU",
              node: {
                id: "joint-LjcTxrSJqQ",
                applicationFamilyId: null,
                archivedAt: null,
                branch: "WS",
                category: "NON_REGISTERED",
                closedAt: null,
                createdAt: "2024-01-22T18:21:35Z",
                currency: "CAD",
                requiredIdentityVerification: "fintracVerification",
                unifiedAccountType: "MANAGED_JOINT",
                updatedAt: "2024-01-22T18:21:35Z",
                nickname: null,
                status: "closed",
                accountOwnerConfiguration: null,
                accountFeatures: [],
                accountOwners: [
                  {
                    accountId: "joint-LjcTxrSJqQ",
                    identityId: "identity-9ArKqNCmhnxU1sbZGd91BwDt8Wt",
                    accountNickname: null,
                    clientCanonicalId: "user-fdyu4vuuyun",
                    accountOpeningAgreementsSigned: false,
                    name: " Li",
                    email: "ylilarry@gmail.com",
                    ownershipType: "primary",
                    activeInvitation: null,
                    __typename: "AccountOwner",
                  },
                ],
                type: "joint",
                __typename: "Account",
                custodianAccounts: [],
                linkedAccount: null,
              },
              __typename: "AccountEdge",
            },
          ],
          __typename: "AccountConnection",
        },
        __typename: "Identity",
      },
    },
  };
}
