name: Publish package to GitHub Packages
on:
  push:
    branches: ["release"]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - run: ./initenv.bash
      - run: |
          source ./devenv.bash
          npm ci
          npm run build
